version: '3.8'

services:
  mongodb:
    image: mongo:5.0.16
    env_file:
      - .env
    container_name: $MONGODB_NAME
    restart: always
    ports:
      - $MONGODB_PORT:$MONGODB_PORT
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGODB_USER
      MONGO_INITDB_ROOT_PASSWORD: $MONGODB_PASSWORD
      MONGO_INITDB_DATABASE: $MONGODB_NAME
    
