version: '3.8'

services:
  mongodb:
    container_name: ufabc-next-users
    image: mongo:5.0.15
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadm
      - MONGO_INITDB_ROOT_PASSWORD=secret
      - MONGO_INITDB_DATABASE=ufabc-next-users
    restart: always
    ports:
      - "27017:27017"
   
    
