#!/usr/bin/env sh

. "$(dirname "$0")/_/husky.sh"

echo "----------------------------------------------"
echo "the correct sintax is type(scope?): subject "
echo "type examples: feat, chore, test, fix"
echo "options examples: controller, config, view"
echo "subject should describe what do you implements"
echo "----------------------------------------------"
npx commitlint --edit $1 
