#!/usr/bin/env sh

. "$(dirname "$0")/_/husky.sh"

echo -e "\e[32mRunning commit message validator\e[0m" 
echo "teste"

if npx commitlint --edit $1 = "0" 
then 
  echo "commit message is standarnized"
else
  echo "commit message isn't standarnized"
  echo "the correct sintax is type(scope?): subject "
  echo "type examples: feat, chore, test, fix"
  echo "options examples: controller, config, view"
  echo "subject should describe what do you implements"
  echo "if you have problems consider use of fit commit --amend -m \"new message\""

  exit 1 
fi