#!/usr/bin/env sh

. "$(dirname "$0")/_/husky.sh"

if npx commitlint --edit $1 = "1";
then 
  echo "commit message isn't standarnized"
  echo "the correct sintax is type(scope?): subject "
  echo "type examples: feat, chore, test, fix"
  echo "options examples: controller, config, view"
  echo "subject should describe what do you implements"
  exit 1
fi