#!/usr/bin/env sh

. "$(dirname "$0")/_/husky.sh"

highlightText() {
  string=$1
  #echo -e allows scape characters
  echo -e "\e[32m$string\e[0m" 
}


highlightText "Running tests" 
pnpm test  

highlightText "Running lint" 
pnpm lint --fix

highlightText "Running commit message validator" 
npx commitlint --edit $1

highlightText "Running branch validator" 

local_branch="$(git rev-parse --abbrev-ref HEAD)"

valid_branch_regex="^((feature|hotfix|bugfix)\/.+)[a-z0-9._-]{2,20}"

message="This branch violates the branch naming rules. Please rename your branch."

if [[ ! $local_branch =~ $valid_branch_regex ]]
then
    echo "$message"
    exit 1
fi

exit 0


