#!/usr/bin/env sh

. "$(dirname "$0")/_/husky.sh"

#echo -e allows scape characters 
echo -e "\e[32mrunning tests\e[0m"
pnpm test  

echo "running lint"
pnpm lint --fix

echo "validate branch name"

local_branch="$(git rev-parse --abbrev-ref HEAD)"

valid_branch_regex="^((feature|hotfix|bugfix)\/.+)[a-z0-9._-]{2,20}"

message="This branch violates the branch naming rules. Please rename your branch."

if [[ ! $local_branch =~ $valid_branch_regex ]]
then
    echo "$message"
    exit 1
fi

exit 0

