#!/usr/bin/env sh

. "$(dirname "$0")/_/husky.sh"

highlightText() {
  string=$1
  #echo -e allows scape characters
  echo -e "\e[32m$string\e[0m" 
}


# highlightText "Running tests" 
# pnpm test  

# highlightText "Running lint" 
# pnpm lint --fix

# highlightText "Running commit message validator"

# npx commitlint $1 
# # isStandarnizedCommit =  $?
# # echo $isStandarnizedCommit
# # if isStandarnizedCommit= "0"
# #   then 
# #     echo "commit message is standarnized"
# #     exit 0
# # else
# #   echo "commit message isn't standarnized"
# #   echo "the correct sintax is type(scope?): subject "
# #   echo "type examples: feat, chore, test, fix"
# #   echo "options examples: controller, config, view"
# #   echo "subject should describe what do you implements"
# #   echo "if you have problems consider use of fit commit --amend -m \"new message\" --no-verify"
# #   git commit --amend -m \"fix: wrong message\" --no-verify
# #   exit 1 
# # fi




echo "testando retorno"
echo $?

highlightText "Running branch validator" 

local_branch="$(git rev-parse --abbrev-ref HEAD)"

valid_branch_regex="^((feature|hotfix|bugfix)\/.+)[a-z0-9._-]{2,20}"

message="This branch violates the branch naming rules. Please rename your branch."

if [[ ! $local_branch =~ $valid_branch_regex ]]
then
    echo "$message"
    exit 1
fi

exit 0


